name: MdToPdfConversion
permissions: write-all
on: 
  push:
    branches: main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc and convert all Markdown Files
        run: |
          # sudo apt-get -y update
          # sudo apt-get -y upgrade
          sudo apt-get -y install pandoc
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo pandoc -v

          gh repo clone imagineMaggots/Bachelor-Thesis
          cd Bachelor-Thesis


          # iterate over all directories
          for dir in *; do
            # check if there are subdirectories
            if [ -d dir ]; then
              echo "checking directory $dir for Markdown-files"
              cd $dir
            fi
            for mdfile in *; do
              if [[ $mdfile = *.md ]]; then
                echo "Compiling $mdfile"

                # Pandoc Conversion to .tex and .pdf
                pandoc "$mdfile" -o ${mdfile/.md/}.pdf
                echo "created ${mdfile/.md/}.pdf"
                pandoc "$mdfile" -s -o ${mdfile/.md/}.tex
                echo "created ${mdfile/.md/}.tex"


                # echo "files=${printf '%s' *.md}" >> $GITHUB_OUTPUT
                fi
              cd ..
            done
            # root dir
            echo "we're back at the root"
            for mdfile in *; do
              if [[ $mdfile = *.md ]]; then
                echo "Compiling $mdfile"

                # Pandoc Conversion to .tex and .pdf
                pandoc "$mdfile" -o ${mdfile/.md/}.pdf
                echo "created ${mdfile/.md/}.pdf"
                pandoc "$mdfile" -s -o ${mdfile/.md/}.tex
                echo "created ${mdfile/.md/}.tex"
              
                # echo "files=${printf '%s' *.md}" >> $GITHUB_OUTPUT
              fi
            done
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
