# Simple workflow for deploying static content to GitHub Pages
name: Convert Markdown to LaTeX via pandoc

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  simple:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      
      - run: for mdfile in *.md; do pandoc $mdfile -s -o ${mdfile/.md/}.tex; pandoc $mdfile -o ${mdfile/.md/}.pdf; done
  
      - uses: docker://pandoc/latex:3.5
        with:
          args: --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
