name: MdToPdfConversion
permissions: write-all
on: 
  push:
    branches: main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc and convert all Markdown Files into tex
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install pandoc
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo pandoc -v

          gh repo clone imagineMaggots/Bachelor-Thesis
          basedir="Bachelor-Thesis"
          cd "./$basedir"
          echo "Entered $basedir"

          convert_markdown_to_tex_and_pdf_recursively ()
          {
            local rootDir=$1
            echo "in $rootDir"

            for dir in *; do                             # regex: should only consider directories
              
              # enter any given subdirectories
              if [[ -d $dir ]]; then                                    # if statement just to make sure
                echo "Trying to enter $dir"
                cd "./$dir"
                echo "Entered $dir"
              
                convert_markdown_to_tex_and_pdf_recursively "$dir" # note: in quotation marks for possible spaces (which a shell interprets as seperators/delimiters btw. function and options (or parameters or...)
              fi
              # now we know that there are no more subdirectories
              
              for mdfile in ${dir/*.md}; do          # regex: only considers markdown-files
                # .md-file already exists? convert it to .tex, otherwise create first a placeholder
                if [[ -e $mdfile ]]; then
                    pandoc "$mdfile" -s -o ${mdfile/.md/}.tex      # regex: cuts off .md-file-ending
                    # pandoc "$mdfile" -s -o ${mdfile/.md/].pdf    # regex: cuts off .md-file-ending
                    echo "Successfully converted $mdfile!"
                else
                    echo "### placeholder" >> $mdfile
                fi
              done
              
              cd ..
            done

            
          }
          
          convert_markdown_to_tex_and_pdf_recursively "$basedir"
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
