name: MdToPdfConversion
permissions: write-all
on: 
  push:
    branches: main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc and convert all Markdown Files
        run: |
          #sudo apt-get -y update
          #sudo apt-get -y upgrade
          #sudo apt-get -y install pandoc
          #sudo apt-get install texlive-latex-base
          #sudo apt-get install texlive-fonts-recommended
          #sudo apt-get install texlive-fonts-extra
          #sudo pandoc -v

          gh repo clone imagineMaggots/Bachelor-Thesis
          basedir="Bachelor-Thesis"
          cd "$basedir"

          # find all files and puts them in a temporary text-file
          echo "{find "." -type f}" 
          


          # pandoc "$mdfile" -s -o ${mdfile/.md/}.tex
          
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
