name: MdToPdfConversion
permissions: write-all
on: 
  push:
    branches: main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc and convert all Markdown Files
        run: |
          # sudo apt-get -y update
          # sudo apt-get -y upgrade
          # sudo apt-get -y install pandoc
          # sudo apt-get install texlive-latex-base
          # sudo apt-get install texlive-fonts-recommended
          # sudo apt-get install texlive-fonts-extra
          # sudo pandoc -v

          gh repo clone imagineMaggots/Bachelor-Thesis
          cd Bachelor-Thesis

          # converts all .md files to .pdf and .tex
          # arguments:
          #   dir: current working directory. doesn't necessarily have to contain Markdown-files 
          function conversion ()
          {
            local dir=$1
            
            # check for any subdirectories
            if [[ -d $dir ]]; then
              cd "$dir"
              echo "success in entering directory $dir..."

              conversion "$dir"

              echo "leaving $dir..."
              cd ..
            else
              # check for any markdown files
              for mdfile in *; do
                if [[ $mdfile = *.md ]]; then
                  echo "Compiling $mdfile"

                # Pandoc Conversion to .tex and .pdf
                #  pandoc "$mdfile" -o ${mdfile/.md/}.pdf
                #  echo "successfully created ${mdfile/.md/}.pdf"
                #  pandoc "$mdfile" -s -o ${mdfile/.md/}.tex
                #  echo "successfully created ${mdfile/.md/}.tex"


                # echo "files=${printf '%s' *.md}" >> $GITHUB_OUTPUT
                fi
              done
            fi
          }

          # iterates over all directories recursively
          for dir in *; do conversion "$dir"; done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output
