name: MdToPdfConversion
permissions: write-all
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Pandoc and convert all Markdown Files
        run: |
          sudo apt-get -y update
          sudo apt-get -y upgrade
          sudo apt-get -y install pandoc
          sudo pandoc -v

          gh repo clone imagineMaggots/Bachelor-Thesis
          cd Bachelor-Thesis

          for mdfile in *; do
            if [[ $mdfile = *.md ]]; then
              	echo "$mdfile"

                # ToDo: Pandoc Conversion to .tex and .pdf
            fi
          done

          gh repo sync
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
