# Simple workflow for deploying static content to GitHub Pages
name: Convert Markdown to LaTeX via pandoc

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  simple:
    runs-on: ubuntu-22.04
    steps:
    - uses: docker://pandoc/core:3.5
      with: 
        args: "--help"
