# Simple workflow for deploying static content to GitHub Pages
name: Convert Markdown to LaTeX via pandoc

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  simple:
    image:
      name: pandoc/core
      entrypoint: ["/bin/sh", "-c"]
    script:
      - pandoc --help
